### ISSUE TITLE
Startup Crash when Integrated Dynamics is not installed

### ISSUE THREAD

**Issue by Cynix32** [shBLOCK/ColossalBattery#1]
Pastebin:
https://pastebin.com/DB0zYjjx

So from the curseforge page, it is stated that only cyclopscore and mekanism is required. However, it is crystal clear from the log that colossal battery requires IEnergyStorageCapacity class from Integrated Dynamics. Not really major issue, as it could be fixed by simply adding Integrated Dynamics to the modpack.

However, it can still be an issue for people who may not know the solution or do not know how to read crashlogs.

**Comment by shBLOCK** [comment]
Thanks for  reporting! This is a problem, will fix it soon.
