### ISSUE TITLE
BROKEN/MISSING RECIPES + microlag

### ISSUE THREAD

**Issue by Cynix32** [shBLOCK/ColossalBattery#2]
These items are "uncraftable" in survival, the recipe also does not show in JEI.

Battery Core
Battery Interface
Basic Battery Filler
Advanced Battery Filler
Ultimate Battery Filler

Can't make a battery in survival due to those broken recipes.

Another issue:
Welp since I can't form a battery in survival due to broken recipes, I made batteries in creative mode.
So to describe, when breaking a block from a battery that was already formed, the game stutters for a very short while.

1. Make and form a battery.
2. Break battery.
3. Each block broken from the previously formed battery will cause a microstutter. Not a big problem on small batteries, annoying when the battery being broken is colossal.

**Comment by shBLOCK** [comment]
Thanks for reporting!

**Comment by shBLOCK** [comment]
How big was your structure? I tested it, and the lag spike is less than 0.5s when breaking a 20*20*20 structure

**Comment by shBLOCK** [comment]
I will try to improve the performance anyway

**Comment by Cynix32** [comment]
Hmmm the test structures i built were ranging from 4^3 to 7^3. The lag spikes per block broken was the same regardless the overall size of battery. As i said it is not even a concern for small structures, but it just kinda gets annoying when breaking a large battery.

But my device is also to blame. Unfortunately, I play on a craptop.

**Comment by shBLOCK** [comment]
The setBlockState function takes up 99.75% of the time when destroy the structure (through forge's debug profiler), and in the setBlockState function, some code that's not been profiled takes up 99.52% of the time, I will release the crafting fix version first
