### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Mr-Donch** [shBLOCK/ColossalBattery#3]
when I shift-click the block  ，the game reports an error

**Comment by shBLOCK** [comment]
Thanks for reporting! Can you send the log file or crash report so that I can know what the error is.

**Comment by mc-kaishixiaxue** [comment]
@Mr-Donch
Is this block you mentioned Battery Interface? The game also crashed when I held shift and right clicked on the Battery Interface on a normal giant battery multiblock (with a Battery Interface). Then this save will never be opened again.(English)
你提到的这个方块是不是电池访问口吗？当我在正常的巨型电池多方块结构（有电池访问口）上按住shift右击电池访问口时，游戏也崩溃了。然后这个存档就再也打不开了。（中文）

Mod list:
> CyclopsCore-1.16.5-1.11.8.jar 
> colossalbattery-1.16-1.0.11.jar 

@shBLOCK I have a crash log: https://paste.ubuntu.com/p/HVNydsc3fd/

**Comment by shBLOCK** [comment]
Thanks for the log, you can install the IntegratedDynamics mod to fix the world for now, I will fix this issue soon.

可以先装上集成动力/动态联合，就可以暂时解决崩溃问题，我会尽快修复

> @Mr-Donch
> Is this block you mentioned Battery Interface? The game also crashed when I held shift and right clicked on the Battery Interface on a normal giant battery multiblock (with a Battery Interface). Then this save will never be opened again.(English)
> 你提到的这个方块是不是电池访问口吗？当我在正常的巨型电池多方块结构（有电池访问口）上按住shift右击电池访问口时，游戏也崩溃了。然后这个存档就再也打不开了。（中文）
> 
> Mod list:
> 
> > CyclopsCore-1.16.5-1.11.8.jar
> > colossalbattery-1.16-1.0.11.jar
> 
> @shBLOCK I have a crash log: https://paste.ubuntu.com/p/HVNydsc3fd/

**Comment by shBLOCK** [comment]
Fixed in 1.0.12
已在1.0.12版本修复
