### ISSUE TITLE
WORLD BREAKING CRASH

### ISSUE THREAD

**Issue by Cynix32** [shBLOCK/ColossalBattery#5]
I was connecting a flux plug (from flux networks mod) to my colossal battery through a battery interface, then it resulted in a crash. Trying to open the world again will just result in another crash, making the world unplayable.

Crashlog:
https://pastebin.com/ChmTmW28

**Comment by Cynix32** [comment]
Looks like I forgot to update the mod. Closing issue

**Comment by shBLOCK** [comment]
Thanks for the trying to help me improve the mod anyways
